#!/usr/bin/perl

use strict;
use warnings;

use Ubic::Service::SimpleDaemon;

my $LOGDIR = '/var/log/haproxy';

Ubic::Service::SimpleDaemon->new({
    bin      => "/usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg",
    stdout   => "$LOGDIR/restart.log",
    stderr   => "$LOGDIR/restart.log",
    ubic_log => "$LOGDIR/ubic.log",
    user     => "root",
});

