#!/usr/bin/perl

### BEGIN INIT INFO
# Provides:	  php5-fcgi
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts php5 as fcgi application
# Description:       starts php5 as fcgi application via ubic
### END INIT INFO

use Ubic::Run;
